### ISSUE TITLE
Crashes with Build 35153

### ISSUE THREAD

**Issue by wernk1** [Gregory365/TPF2-Timetables#9] opened 2023-02-06 10:39 UTC
The Version 1.3 crashes with Build 35153 (new "console" beta) when using the scrollbar.
[stdout.zip](https://github.com/Gregory365/TPF2-Timetables/files/10662141/stdout.zip)

**Comment by pull2play** [comment] 2023-02-06 13:47
He's aware of it - check closed issues for current status.

**Comment by Gregory365** [comment] 2023-03-10 19:36
Caused by same bug as #6

**Comment by Gregory365** [comment] 2023-03-11 12:31
It's difficult to find what is causing this issue. I've narrowed down the crash to the line:
`UIState.boxlayout2:removeItem(menu.scrollAreaConstraint)`

The same issue also occurs when changing stations too. However, sometimes it crashes, sometimes it doesn't. The error message makes it seem like its an issue with the API rather than this mod but it's hard to tell. The message `expected string, received sol.UI::ScrollArea*` doesn't make much sense in this context.

```
urban_games/train_fever/src/Lib/UI/Component.cpp:1819: void __cdecl UI::CComponent::RemoveChild(class UI::CComponent *): Assertion `!m_childMutex' failed.
PANIC: unprotected error in call to Lua API (stack index 1, expected string, received sol.UI::ScrollArea*)
Received SIGABRT
Heap corruption detected!
```

It seems related to [this issue with the build with collisions mod](https://www.transportfever.net/thread/17979-build-with-collision/?pageNo=5). Second [link to steam discussion](https://steamcommunity.com/groups/transportfever2_mac_vulkan/discussions/7/3762231030857653321/)

Potentially could be caused by a faulty assertion `!m_childMutex`. Either way its very hard to solve without knowing what this assertion is checking.

It seems UG has quite a few issues with crashing at the moment anyway when scanning through the steam discussions, so I'm going to postpone this fix again until stability has improved a bit. 

If anyone has any suggestions or ideas then feel free to add to this issue, the [discord](https://discord.gg/7KbVP8Fr6Z), or [the steam discussion](https://steamcommunity.com/workshop/filedetails/discussion/2408373260/3431200155178875294/)

**Comment by Gregory365** [comment] 2023-03-12 12:02
The `!_mchildMutex` might be related to [Mutex Objects](https://learn.microsoft.com/en-us/windows/win32/sync/mutex-objects). This would make sense as to why the error sometimes occurs and sometimes doesn't because Mutex objects are to do with managing which thread own shared resource.

This would mean that sometimes a crash occurs (when the resource is owned by another thread). And sometimes it doesn't (when the resource isn't owned by another thread).

Debugging threading issues is very hard, any help would be appreciated.

**Comment by Gregory365** [comment] 2023-03-12 21:55
@wernk1 @pull2play Please can you confirm this is fixed on the [scrollbarCrash](https://github.com/Gregory365/TPF2-Timetables/tree/scrollbarCrash) branch?

**Closed** 2023-03-14 13:26 UTC
Labels: bug, duplicate

**Comment by wernk1** [comment] 2023-03-14 13:48
It's ok now.
