### ISSUE TITLE
Multiple crashes

### ISSUE THREAD

**Issue by stebbo63** [Gregory365/TPF2-Timetables#65] opened 2024-01-24 21:54 UTC
I have been using this script for some time without any issues.  I exclusively use the auto unbunch feature.
This morning, I had three crashes in a row, all saying pretty much the same thing.  I have pasted the tail of the crash log below.

After the 3rd crash, I went through all the timetables and found the following possible causes.

1. There were timetables set (for auto unbunch) for lines with only 1 train.
2. There were lines ticked on the left hand side, but no timetable was set.  (NOTE: I always set a timetable, so this was not like this at some time before the crash).

I am happy to help with a little bit of investigation.

Thanks,
Chris.

Timetables coroutine error: userdata: 0000013D9AC3A548
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
Timetables failed to resume normal coroutine.
__CRASHDB_DUMP__ 4d3ef5c8-91a5-47ec-9ac9-1a694b32ee58
Attempting to write crash save to "crash_Reno Transport 16_2024-01-25_08-32-09"
available disk space: 37411 MB
[2024-01-25 08:32:09] Saving to file C:/Program Files (x86)/Steam/userdata/900474849/1066780/local/save/crash_Reno Transport 16_2024-01-25_08-32-09.sav
save game failed: Allocation error : not enough memory: iostream stream error
Saving...: 1.473 ms
Additional info extracted from the previous state:
Uncaught exception while in class UI::CSelector
Exception type: Lua exception

This error is usually caused by modding. Some game resources contain incorrect data.

Details:

Error message: 

File name: D:/SteamLibrary/steamapps/workshop/content/1066780/2918585390/res/config/game_script/timetable_gui.lua

Key: game/res/gameScript/timetable_gui.lua_guiUpdate

Minidump: C:/Program Files (x86)/Steam/userdata/900474849/1066780/local/crash_dump/4d3ef5c8-91a5-47ec-9ac9-1a694b32ee58.dmp (failed)

UI Component Hierarchy: 
 type: class UI::CGameUI, id = "", name = "CGameUI", styleClasses = {"top-gamebar-visible"}
 type: class UI::CMenuUI, id = "", name = "MenuUI", styleClasses = {}
 type: class UI::CComponent, id = "", name = "wrap", styleClasses = {"platform-desktop", "ui-classic", "input-mouse", "gamepad-type-xbox"}

Mod: "Timetables" (*2918585390, 1) (consider removing this mod and contacting the mod author)

In file: urban_games/train_fever/src/Lib/lua/State.cpp:646

In function: void __cdecl lua::State::Call(int,int)

__CRASHDB_CRASH__ struct lua::LuaException: urban_games/train_fever/src/Lib/lua/State.cpp:646: void __cdecl lua::State::Call(int,int):

**Comment by stebbo63** [comment] 2024-01-25 01:20
p.s.  I don't ever set a timetable for a line with only 1 train.  However, in this current game I have removed trains from some lines which will leave it with only 1 train.

**Comment by Gregory365** [comment] 2024-01-25 17:30
Thanks for the report, the information about your timetable setup is useful too. 

Unfortunately, the error raised in the stdout.txt doesn't identify the issue. I appreciate the stdout.txt may now be overridden but if you do still have it can you upload the full stdout.txt? The file might have a different name with the save name and time of the crash.

In the meantime, I'll try to see if I can reproduce a crash for:
1. A line with only one train, with an "auto unbunch" timetable.
2. An enabled timetable with nothing else setup.

**Comment by stebbo63** [comment] 2024-01-25 22:18
[4d3ef5c8-91a5-47ec-9ac9-1a694b32ee58_stdout.txt](https://github.com/Gregory365/TPF2-Timetables/files/14058206/4d3ef5c8-91a5-47ec-9ac9-1a694b32ee58_stdout.txt)
[f9da92bb-31a0-4483-b003-31574d8eb320_stdout.txt](https://github.com/Gregory365/TPF2-Timetables/files/14058207/f9da92bb-31a0-4483-b003-31574d8eb320_stdout.txt)

**Comment by stebbo63** [comment] 2024-01-25 22:19
I have two of the three files.  Hopefully they pasted above.

**Comment by stebbo63** [comment] 2024-01-30 04:47
[19a0b939-5629-4cbf-838f-c7c97cb062ca_stdout.txt](https://github.com/Gregory365/TPF2-Timetables/files/14092899/19a0b939-5629-4cbf-838f-c7c97cb062ca_stdout.txt)
[89f46fd6-9325-46f7-9053-0fe22d446ae6_stdout.txt](https://github.com/Gregory365/TPF2-Timetables/files/14092900/89f46fd6-9325-46f7-9053-0fe22d446ae6_stdout.txt)
[c37c9a3f-cc72-4474-ab4c-b40e9cf3b541_stdout.txt](https://github.com/Gregory365/TPF2-Timetables/files/14092901/c37c9a3f-cc72-4474-ab4c-b40e9cf3b541_stdout.txt)


another three crashes today.  Two nominate this script, one was a memory error.

**Comment by Gregory365** [comment] 2024-02-09 22:41
Apologies for the late reply. All of these errors seem to be caused by a lack of memory.
4d3ef5c8... `Allocation error : not enough memory`
f9da92bb... `Allocation error : not enough memory`
19a0b939... `Allocation error : not enough memory`
89f46fd6... `Allocation error : not enough memory:`
c37c9a3f... `Assertion Failure: Assertion `false && "Out of memory"' failed.`

While some of these errors seem to occur in timetables mod, they don't make any sense to me and I would assume they are side affects of a lack of memory. The c37c9a3f... error isn't related to the timetables mod at all.

I'm going to close as won't fix as I don't think it is reasonable for this mod to handle low memory conditions that the game can often not handle itself. Also the errors raised are just rethrowing errors from the coroutine library.

**Closed by Gregory365** 2024-02-09 22:41 UTC
Labels: needs repro

**Comment by stebbo63** [comment] 2024-02-21 20:18
Hi Greg,
thanks for the responses.  It's strange that I went through a period of memory crashes around that time, but I have 64GB on the machine and rarely fill it.  The game has been stable since those crashes though, so something was off.
Thanks for the great mod.
Cheers,
Chris.
