### ISSUE TITLE
Timetables coroutine error

### ISSUE THREAD

**Issue by Tawa-chan** [Gregory365/TPF2-Timetables#66] opened 2024-02-17 18:27 UTC
Hey, I've been getting this error message when playing on my current save game. It appears in both console and stdout.

Timetables coroutine error: C:/Steam/steamapps/workshop/content/1066780/2918585390/res/scripts/celmi/timetables/timetable.lua:699: attempt to index local 'slot' (a nil value)
Timetables failed to resume dead coroutine. 

As with Issue #55 it continues to spam this into the console and stdout. Timetable slots are ignored and trains are way out of their slots or are stuck at a station.

This issue has started after I had the game crash a while ago. Classic "An internal error occured" message. This is heavily modded savegame so these kinds of crashes happen once in a while. I then reloaded from the last autosave and ever since then that issue has been appearing.

The crash did however happen while using the timetables GUI. While deleting an arrival/depature slot I pressed the "X" (not yes or no) on the small delete confirmation window while the main GUI was closed. I have not managed to reproduce that error in a vanilla save with only timetables enabled. Not sure if that might be relevant for the error. I do not have the stdout from that incident sadly, however if needed I can try to reproduce it in the same savegame and see if it happens again.

Thanks!

**Comment by Tawa-chan** [comment] 2024-02-20 17:53
UPDATE

**Comment by Tawa-chan** [comment] 2024-02-21 16:09
Update 2:

Sadly the error does persist. I loaded the savegame from yesterday where the timetables were working again, however now it seems to break with the same error message as before. My guess it somehow doesn't save properly and therefore when loading the savegame the timetables break. 
Any idea on how to fix this?

**Comment by Gregory365** [comment] 2024-02-21 16:46
- Caused by the slot being nil on line `timetable.minToSec(slot[1], slot[2])`

Can you please upload a copy of your sav.lua file?

**Comment by Gregory365** [comment] 2024-02-21 16:50
Thanks for highlighting what caused the bug, I'll try to reproduce the issue myself and fix it soon.

**Comment by Tawa-chan** [comment] 2024-02-28 00:42
Hey, 
any luck with reproducing the issue? I've been trying to find a workaround for the moment but sadly it only works by re-installing every time which gets a bit annoying.
Thanks!

**Comment by Gregory365** [comment] 2024-03-03 13:34
Hi, apologies for the delay in getting this fixed.

This bug is caused by having a timetable in ArrDep mode with a station with no slots.

Vehicles will now depart instantly if no timetable slots are defined.

**Comment by Gregory365** [comment] 2024-03-03 15:34
Fixed in v1.3.5

**Closed by Gregory365** 2024-03-03 15:34 UTC
Labels: bug, needs repro
