### ISSUE TITLE
Dots at the line table are white

### ISSUE THREAD

**Issue by wernk1** [Gregory365/TPF2-Timetables#14] opened 2023-03-17 12:26 UTC
Many of the dots in front of the line numbers at the line table are white. Why are there no colors?

**Comment by Gregory365** [comment] 2023-03-17 12:32
All of them have colours for me
![image](https://user-images.githubusercontent.com/36188440/225905492-f26f560b-0988-4224-acca-407c9ae03d14.png)

Are you using any colours mod?

**Comment by wernk1** [comment] 2023-03-19 14:52
No, I don't use a color mod. Here's a view of my window.
[timetable01.zip](https://github.com/Gregory365/TPF2-Timetables/files/11011341/timetable01.zip)

**Comment by Gordon-Dry** [comment] 2023-03-19 23:51
@wernk1 you can drag&drop image files directly into here:
![timetable01](https://user-images.githubusercontent.com/29145213/226217577-a251967d-1e95-4981-bdc4-95876b59a9b7.jpg)

**Comment by Gregory365** [comment] 2023-03-20 16:01
Hmm. I still can't seem to replicate this. Are you using any custom colours?
![image](https://user-images.githubusercontent.com/36188440/226398399-906faebe-6591-43ec-8c2d-b0b0298eddce.png)

Do the timetable colours fix themselves when you change the colour of the line in the line manager?

**Comment by wernk1** [comment] 2023-03-21 13:32
Yes, they do.

**Comment by Gregory365** [comment] 2023-06-12 19:36
Closing as the cause is unknown and changing the colours works.

**Closed by Gregory365** 2023-06-12 19:36 UTC
Labels: wontfix
